---
- name : practice playbook
  hosts : all
  become : true
  tasks :
    - name : install htop
      yum :
        name : htop
        state : absent

    - name : install nginx
      yum :
        name : nginx
        state : absent

    - name : starting nginx
      service :
        name : nginx
        state : started
